- name: Azure üzerinde Ansible belgeleri
  href: ./index.yml
- name: Genel Bakış
  items:
    - name: Azure üzerinde Ansible hakkında
      href: ./ansible-overview.md
- name: Hızlı Başlangıçlar
  expanded: true
  items:
    - name: Ansible çözüm şablonunu CentOS’a dağıtma
      href: ./ansible-deploy-solution-template.md
    - name: Linux sanal makinelerine Ansible’ı yükleme
      href: ./ansible-install-configure.md
      maintainContext: true
    - name: Cloud Shell’de playbook çalıştırma
      href: ./ansible-run-playbook-in-cloudshell.md
    - name: Linux Sanal Makineleri ile çalışma
      expanded: true
      items:
        - name: Linux sanal makinelerini yapılandırma
          href: ./ansible-create-vm.md
          maintainContext: true
        - name: Linux sanal makinelerini yönetme
          href: ./ansible-manage-linux-vm.md
          maintainContext: true
- name: Öğreticiler
  items:
    - name: Azure Application Gateway
      items:
        - name: Web trafiğini yönetme
          href: ./ansible-create-configure-application-gateway.md
    - name: Azure App Service
      items:
        - name: Uygulamaları yapılandırma
          href: ./ansible-create-configure-azure-web-apps.md
        - name: Uygulamaları ölçeklendirme
          href: ./ansible-scale-azure-web-apps.md
    - name: Azure DevTest Labs
      items:
        - name: Laboratuvarları yapılandırma
          href: ./ansible-devtest-labs-configure.md
    - name: Azure Kubernetes Hizmeti (AKS)
      items:
        - name: AKS kümelerini yapılandırma
          href: ./ansible-create-configure-aks.md
        - name: Azure CNI ağını yapılandırma
          href: ./ansible-aks-configure-cni-networking.md
        - name: Kubenet ağını yapılandırma
          href: ./ansible-aks-configure-kubenet-networking.md
        - name: AKS kümesinde RBAC rollerini yapılandırma
          href: ./ansible-aks-configure-rbac.md
    - name: Azure HDInsight
      items:
        - name: Kümeleri yapılandırma
          href: ./ansible-azure-hdinsight-configure.md
    - name: Azure Service Bus
      items:
        - name: Kuyrukları yapılandırma
          href: ./ansible-service-bus-queue-configure.md
        - name: Konuları yapılandırma
          href: ./ansible-service-bus-topic-configure.md
    - name: Veritabanı
      items:
        - name: MySQL için Azure Veritabanı’nı yapılandırma
          href: ./ansible-create-configure-mysql.md
        - name: Azure Cosmos DB hesaplarını yapılandırma
          href: ./ansible-data-cosmos-configure.md
        - name: Redis için Azure Cache’i yapılandırma
          href: ./ansible-data-cache-for-redis-configure.md
    - name: Dinamik envanter
      items:
        - name: Azure kaynaklarınızı yönetme
          href: ./ansible-manage-azure-dynamic-inventories.md
    - name: Sanal makineler
      items:
        - name: Paylaşılan Görüntü Galerisi oluşturma
          href: ansible-vm-create-from-shared-generalized-image.md
    - name: Sanal makine ölçek kümeleri
      items:
        - name: Yapılandırma
          href: ./ansible-create-configure-vmss.md
        - name: Dağıtma
          href: ./ansible-deploy-app-vmss.md
        - name: Otomatik Ölçeklendirme
          href: ./ansible-auto-scale-vmss.md
        - name: Özel görüntüyü güncelleştirme
          href: ./ansible-vmss-update-image.md
        - name: Paylaşılan Görüntü Galerisi oluşturma
          href: ansible-vm-create-from-shared-generalized-image.md
    - name: Sanal ağ
      items:
        - name: Eşlemeyi yapılandırma
          href: ./ansible-vnet-peering-configure.md
        - name: Yol tablolarını yapılandırma
          href: ./ansible-create-configure-route-table.md
- name: Örnekler
  items:
    - name: Azure için Ansible laboratuvarları
      href: 'https://github.com/microsoft/ansiblelabs'
    - name: Ansible Azure playbook örnekleri
      href: 'https://github.com/Azure-Samples/ansible-playbooks'
- name: Başvuru
  items:
    - name: Playbook rolleri
      items:
        - name: azure_module
          href: 'https://galaxy.ansible.com/Azure/azure_modules/'
        - name: azure_preview_module
          href: 'https://galaxy.ansible.com/Azure/azure_preview_modules'
    - name: Sürümler ve özellikler
      href: ./ansible-matrix.md
    - name: Tüm Azure modülleri
      href: 'https://docs.ansible.com/ansible/latest/modules/list_of_cloud_modules#azure'
- name: Araçlar
  items:
    - name: Ansible için Visual Studio Code uzantısı
      href: 'https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible'