- name: Azure AD rolleriyle ilgili belgeler
  href: index.yml
- name: Genel Bakış
  items:
    - name: Azure AD RBAC nedir?
      href: custom-overview.md
- name: Hızlı Başlangıçlar
  items:
    - name: Kullanıcılara rol atama
      href: ../fundamentals/active-directory-users-assign-role-azure-portal.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context
- name: Kavramlar
  items:
    - name: Azure AD rollerini anlama
      href: concept-understand-roles.md
    - name: Rolleri Karşılaştır
      items:
        - name: Azure ile Azure AD rollerini karşılaştırma
          href: ../../role-based-access-control/rbac-and-directory-admin-roles.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context
        - name: Microsoft 365 rolleri
          href: m365-workload-docs.md
    - name: Grup tabanlı rol atamaları
      href: groups-concept.md
    - name: Yönetim birimleri
      href: administrative-units.md
    - name: Güvenlik
      items:
        - name: Rol güvenliği planlaması
          href: security-planning.md
        - name: Acil durum hesabı oluşturma
          href: security-emergency-access.md
- name: Nasıl yapılır kılavuzları
  items:
    - name: Rol tanımlarını listeleme
      href: role-definitions-list.md
    - name: Rol atamalarını listeleme
      items:
        - name: Rol atamalarını listeleme
          href: view-assignments.md
        - name: Gruplar için rol atamalarını listeleyin
          href: groups-view-assignments.md
    - name: Rolleri atama
      items:
        - name: Kullanıcılara rol atama
          href: manage-roles-portal.md
        - name: Rol atanabilir grup oluşturma
          href: groups-create-eligible.md
        - name: Gruplara roller atama
          href: groups-assign-role.md
        - name: PIM'de grubun role uygun olmasını sağlama
          href: groups-pim-eligible.md
        - name: PowerShell kullanarak kapsama sahip roller atama
          href: custom-assign-powershell.md
        - name: Graph API kullanarak rol atama
          href: custom-assign-graph.md
    - name: Rol atamalarını kaldırma
      items:
        - name: Rol atamalarını gruplardan kaldır
          href: groups-remove-assignment.md
    - name: Özel roller oluşturma
      items:
        - name: Özel rol oluşturma
          href: custom-create.md
        - name: Kurumsal uygulamalar için özel roller oluşturma
          href: custom-enterprise-apps.md
        - name: Sınırsız uygulama kaydı oluşturma
          href: quickstart-app-registration-limits.md
    - name: Yönetim birimleri
      items:
        - name: Ekleme ve yönetme
          href: admin-units-manage.md
        - name: Kullanıcı ekleme ve yönetme
          href: admin-units-add-manage-users.md
        - name: Grup ekleme ve yönetme
          href: admin-units-add-manage-groups.md
        - name: Kapsam ile rol atama
          href: admin-units-assign-roles.md
    - name: Temsilci
      items:
        - name: Uygulama yöneticisi rolüne temsilci seçme
          href: delegate-app-roles.md
        - name: Personelim temsilcisi
          href: my-staff-configure.md
    - name: Sorun giderme
      items:
        - name: Gruplara atanan rollerin sorunlarını giderme
          href: groups-faq-troubleshooting.md
        - name: Yönetim birimlerinin sorunlarını giderme
          href: admin-units-faq-troubleshoot.md
        - name: Azure AD için destek alma
          href: ../fundamentals/active-directory-troubleshooting-support-howto.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context
- name: Başvuru
  items:
    - name: Yerleşik roller
      href: permissions-reference.md
    - name: Göreve göre en az ayrıcalıklı roller
      href: delegate-by-task.md
    - name: Varsayılan kullanıcı izinleri
      href: ../fundamentals/users-default-permissions.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context
    - name: Özel rol izinleri
      items:
        - name: Uygulama kaydı izinleri
          href: custom-available-permissions.md
        - name: Enterprise uygulama izinleri
          href: custom-enterprise-app-permissions.md
        - name: Uygulama onay izinleri
          href: custom-consent-permissions.md
    - name: Azure AD hizmet sınırlamaları
      href: ../enterprise-users/directory-service-limits-restrictions.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context
    - name: Azure AD PowerShell
      href: /powershell/azure/active-directory/overview
    - name: Graph API
      href: /graph/api/overview