- name: Azure Arc özellikli Kubernetes için belgeler
  href: index.yml
- name: Genel bakış
  items:
    - name: Arc özellikli Kubernetes
      href: overview.md
- name: Nasıl yapılır kılavuzları
  items:
    - name: Azure Arc’a bağlanma
      items:
        - name: Kümeye bağlanma
          href: connect-cluster.md
        - name: Hizmet sorumlusu ekleme
          href: create-onboarding-service-principal.md
    - name: Yönetme
      items:
        - name: GitOps kullanarak yapılandırmaları dağıtma
          href: use-gitops-connected-cluster.md
        - name: GitOps kullanarak Helm chart’ları dağıtma
          href: use-gitops-with-helm.md
        - name: Azure İlkesi’ni kullanarak GitOps uygulama
          href: use-azure-policy.md
        - name: Kapsayıcılar için Azure İzleyici kullanarak izleme
          href: ../../azure-monitor/insights/container-insights-enable-arc-enabled-clusters.md?toc=/azure/azure-arc/kubernetes/toc.yml
        - name: Azure İlkesi kullanarak giriş denetimi ilkeleri
          href: ../../governance/policy/concepts/policy-for-kubernetes.md?toc=/azure/azure-arc/kubernetes/toc.yml
        - name: IoT iş yüklerini dağıtma
          href: deploy-azure-iot-edge-workloads.md
    - name: Sorun giderme
      href: Troubleshooting.md
- name: Başvuru
  items:
    - name: Azure İlkesi yerleşik ilkeler
      displayName: 'samples, policies, definitions'
      href: policy-reference.md