- name: Azure Arc özellikli Kubernetes
  href: index.yml
- name: Genel Bakış
  items:
    - name: Azure Arc özellikli Kubernetes hakkında
      href: overview.md
    - name: Azure Arc doğrulama programı
      href: validation-program.md
- name: Hızlı Başlangıçlar
  items:
    - name: Bir kümeyi Azure yaya bağlama
      href: quickstart-connect-cluster.md
- name: Öğreticiler
  items:
    - name: GitOps kullanarak yapılandırmaları dağıtma
      href: tutorial-use-gitops-connected-cluster.md
    - name: Gilar ile CI/CD 'yi uygulama
      href: tutorial-gitops-ci-cd.md
- name: Kavramlar
  items:
    - name: Aracı Mimarisi
      href: conceptual-agent-architecture.md
    - name: Konfigürasyonlar ve Gilar
      href: conceptual-configurations.md
    - name: Küme uzantıları
      href: conceptual-extensions.md
    - name: Küme bağlantısı
      href: conceptual-cluster-connect.md
    - name: Özel konumlar
      href: conceptual-custom-locations.md
    - name: Azure RBAC
      href: conceptual-azure-rbac.md
    - name: Sık Sorulan Sorular
      href: faq.md
    - name: Gilar kullanarak CI/CD iş akışı
      href: conceptual-gitops-ci-cd.md
- name: Nasıl yapılır kılavuzları
  items:
    - name: Hizmet sorumlusu kullanarak küme bağlama
      href: create-onboarding-service-principal.md
    - name: Aracıları yükselt
      href: agent-upgrade.md
    - name: Senaryolar
      items:
        - name: GitOps kullanarak Helm chart’ları dağıtma
          href: use-gitops-with-helm.md
        - name: Azure İlkesi’ni kullanarak GitOps uygulama
          href: use-azure-policy.md
        - name: Küme uzantılarını dağıtma ve yönetme
          href: extensions.md
        - name: Kapsayıcılar için Azure İzleyici kullanarak izleme
          href: ../../azure-monitor/containers/container-insights-enable-arc-enabled-clusters.md?toc=/azure/azure-arc/kubernetes/toc.json
        - name: Azure Defender kullanarak tehdit korumasını zorlama
          href: ../../security-center/defender-for-kubernetes-azure-arc.md?toc=/azure/azure-arc/kubernetes/toc.json
        - name: Azure İlkesi kullanarak giriş denetimi ilkeleri
          href: ../../governance/policy/concepts/policy-for-kubernetes.md?toc=/azure/azure-arc/kubernetes/toc.json
        - name: Kümeye her yerden güvenli bir şekilde bağlanın
          href: cluster-connect.md
        - name: Yetkilendirme denetimleri için Azure AD RBAC kullanma
          href: azure-rbac.md
        - name: Özel konumlar oluşturma
          href: custom-locations.md
        - name: IoT iş yüklerini dağıtma
          href: deploy-azure-iot-edge-workloads.md
    - name: Sorun giderme
      href: Troubleshooting.md
- name: Başvuru
  items:
    - name: Azure İlkesi yerleşik ilkeler
      displayName: 'samples, policies, definitions'
      href: policy-reference.md
    - name: Azure PowerShell
      href: /powershell/module/Az.ConnectedKubernetes/
- name: Kaynaklar
  items:
    - name: Azure Arc hızlı başlangıç
      href: 'https://azurearcjumpstart.io'